# Generated by Django 4.0.5 on 2022-06-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_productos_id_remove_productos_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Nombre',
            field=models.CharField(default=1, max_length=25, verbose_name='Nombre Producto'),
            preserve_default=False,
        ),
    ]
