# Generated by Django 4.0.5 on 2022-06-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Imagen',
            field=models.ImageField(default=1, upload_to='Imagenes Productos'),
            preserve_default=False,
        ),
    ]
