# Generated by Django 4.0.5 on 2022-06-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Descripcion',
            field=models.TextField(default=1, max_length=300, verbose_name='Descripcion Producto'),
            preserve_default=False,
        ),
    ]
