# Generated by Django 4.0.5 on 2022-06-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productos_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productos',
            new_name='ListaP',
        ),
        migrations.RenameField(
            model_name='listap',
            old_name='Nombre',
            new_name='NombreP',
        ),
    ]
