# Generated by Django 4.0.5 on 2022-06-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_productos_listap_rename_nombre_listap_nombrep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listap',
            name='Imagen',
        ),
    ]
