# Generated by Django 4.0.5 on 2022-06-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_listap_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='listap',
            name='Imagen',
            field=models.ImageField(default=1, upload_to='Imagenes Productos'),
            preserve_default=False,
        ),
    ]
