# Generated by Django 4.0.5 on 2022-06-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_listap_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listap',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='ImgProductos'),
        ),
    ]
